name: 'dbt_olist_vip'
version: '1.0.0'

profile: 'dbt_olist_vip'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_olist_vip:
    staging:
      +materialized: view
    marts:
      +materialized: table
